language: cpp
os:
  - linux
  - osx
dist: bionic
osx_image: xcode12u
env:
  # minimal build
  - FEATURES=core
  # full build
  - FEATURES=core,avcodec,avformat,avdevice,avfilter,swresample,swscale,bzip2,iconv,lzma,opus,snappy,soxr,vpx,zlib
  # tools
  - FEATURES=core,ffmpeg,ffplay,ffprobe
  # gpl features
  - FEATURES=core,gpl,postproc,x265,avcodec
addons:
  apt:
    sources:
    - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
      key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
    - yasm
    - ninja-build
    - cmake
  homebrew:
    packages:
    - yasm
    - ninja
before_install:
  # ensure cmake is found in /usr/bin first (otherwise old cmake is used on travis)
  - PATH="/usr/bin:${PATH}"
  - cmake --version
install:
  - cd ${TRAVIS_BUILD_DIR}/vcpkg
  - ./bootstrap-vcpkg.sh -disableMetrics -useSystemBinaries
  - travis_wait 45 ./vcpkg install ffmpeg[${FEATURES}] || { cat ${TRAVIS_BUILD_DIR}/vcpkg/buildtrees/ffmpeg/build-x64-${TRAVIS_OS_NAME}-rel-out.log; false; }
script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build-rel
  - cd build-rel
  - cmake ../test -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake -DFEATURES=${FEATURES//,/;}
  - cmake --build .
  - ctest -V
  - cd ..
  - mkdir build-dbg
  - cd build-dbg
  - cmake ../test -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake -DFEATURES=${FEATURES//,/;}
  - cmake --build .
  - ctest -V
