language: cpp
os:
  - linux
  - osx
dist: bionic
osx_image: xcode12u
env:
  - FEATURES=core
  # vpx broken - see https://github.com/microsoft/vcpkg/pull/13636
  - FEATURES=core,avcodec,avformat,avdevice,avfilter,swresample,swscale,bzip2,lzma,opus,snappy,soxr,wavpack,zlib
addons:
  apt:
    packages:
    - yasm
  homebrew:
    packages:
    - yasm
    - ninja
before_install:
  - cmake --version
install:
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd ${TRAVIS_BUILD_DIR}/vcpkg
  - git checkout `cat ${TRAVIS_BUILD_DIR}/VCPKG_HASH.txt` -d
  - ./bootstrap-vcpkg.sh -disableMetrics
  - travis_wait 45 ./vcpkg install ffmpeg[${FEATURES}] || { cat ${TRAVIS_BUILD_DIR}/vcpkg/buildtrees/ffmpeg/build-x64-${TRAVIS_OS_NAME}-rel-out.log; false; }
script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build-rel
  - cd build-rel
  - cmake ../test -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake -DFEATURES=${FEATURES//,/;}
  - cmake --build .
  - ctest -V
