language: cpp
os:
  - linux
  - osx
dist: focal
osx_image: xcode12u
env:
  # minimal build
  - FEATURES=core
  # full build: core libraries, tools, lgpl features, gpl features
  # BROKEN TOOLS: ffmpeg,ffplay,ffprobe - needs https://github.com/microsoft/vcpkg/pull/13932
  # BROKEN LGPL: mp3lame,theora
  # BROKEN GPL: x265
  - FEATURES=core,avcodec,avformat,avdevice,avfilter,swresample,swscale,bzip2,iconv,lzma,opus,snappy,soxr,vpx,zlib,gpl,postproc
addons:
  apt:
    packages:
    - yasm
    - ninja-build
  homebrew:
    packages:
    - yasm
    - ninja
before_install:
  - cmake --version
install:
  # cannot clone in existing folder so setup vcpkg2 where cache is stored
  - mkdir -p ${TRAVIS_BUILD_DIR}/vcpkg2
  - cd ${TRAVIS_BUILD_DIR}/vcpkg2
  - git remote add origin ${TRAVIS_BUILD_DIR}/vcpkg
  - git fetch origin
  - git checkout `cat ${TRAVIS_BUILD_DIR}/VCPKG_HASH.txt` -d
  - ./bootstrap-vcpkg.sh -disableMetrics -useSystemBinaries
  - travis_wait 45 ./vcpkg upgrade
  - travis_wait 45 ./vcpkg install ffmpeg[${FEATURES}] || { cat ${TRAVIS_BUILD_DIR}/vcpkg2/buildtrees/ffmpeg/build-x64-${TRAVIS_OS_NAME}-rel-out.log; false; }
script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build-rel
  - cd build-rel
  - cmake ../test -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/vcpkg2/scripts/buildsystems/vcpkg.cmake -DFEATURES=${FEATURES//,/;}
  - cmake --build .
  - ctest -V
  - cd ..
  - mkdir build-dbg
  - cd build-dbg
  - cmake ../test -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/vcpkg2/scripts/buildsystems/vcpkg.cmake -DFEATURES=${FEATURES//,/;}
  - cmake --build .
  - ctest -V
cache:
  directories:
  - vcpkg2/installed
