language: cpp
os:
  - linux
  - osx
dist: bionic
osx_image: xcode12u
env:
    # minimal build
    ###################
    - FEATURES=core

    # LGPL full builds
    ###################
    - FEATURES=core,avcodec,avformat,avdevice,avfilter,swresample,swscale,bzip2,iconv,lzma,opus,snappy,soxr,vpx,zlib

    # LGPL features
    ################
    - FEATURES=core,bzip2,avformat
    - FEATURES=core,ffmpeg
    - FEATURES=core,ffplay
    - FEATURES=core,ffprobe
    - FEATURES=core,iconv,avcodec
    - FEATURES=core,lzma,avformat
    - FEATURES=core,nvcodec,avcodec
    - FEATURES=core,mp3lame,avcodec
    - FEATURES=core,opus,avcodec
    # BROKEN
    #- FEATURES=core,theora,avcodec
    - FEATURES=core,snappy,avcodec
    - FEATURES=core,soxr,swresample
    - FEATURES=core,vpx,avcodec
    - FEATURES=core,zlib,avformat

    # GPL features
    ###############
    - FEATURES=core,postproc
    # BROKEN
    #- FEATURES=core,x264,avcodec
    - FEATURES=core,x265,avcodec

addons:
  apt:
    packages:
    - yasm
  homebrew:
    packages:
    - yasm
    - ninja
before_install:
  - cmake --version
install:
  - cd ${TRAVIS_BUILD_DIR}/vcpkg
  - ./bootstrap-vcpkg.sh -disableMetrics
  - travis_wait 45 ./vcpkg install ffmpeg[${FEATURES}] || { cat ${TRAVIS_BUILD_DIR}/vcpkg/buildtrees/ffmpeg/build-x64-${TRAVIS_OS_NAME}-rel-out.log; false; }
script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build-rel
  - cd build-rel
  - cmake ../test -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake -DFEATURES=${FEATURES//,/;}
  - cmake --build .
  - ctest -V
  - cd ..
  - mkdir build-dbg
  - cd build-dbg
  - cmake ../test -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_TOOLCHAIN_FILE=${TRAVIS_BUILD_DIR}/vcpkg/scripts/buildsystems/vcpkg.cmake -DFEATURES=${FEATURES//,/;}
  - cmake --build .
  - ctest -V
