version: 1.0.{build}
image: Visual Studio 2019
environment:
  VCPKG_HASH: 18ab4b72a26284f0df28295ce7bf9b21c96f20f4
  TRIPLET: x64-windows-static-md
  FULL_BUILD: false
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: -t7z -m0=lzma -mx=9

  matrix:
    - FEATURES: core,bzip2
    - FEATURES: core,lzma
    - FEATURES: core,nvcodec
    - FEATURES: core,opus
    - FEATURES: core,snappy
    - FEATURES: core,soxr
    - FEATURES: core,avcodec,vpx
    - FEATURES: core,wavpack
    - FEATURES: core,zlib
    - FEATURES: core,avcodec,avformat,avdevice,avfilter,swresample,swscale,bzip2,lzma,nvcodec,opus,snappy,soxr,vpx,wavpack,zlib
      FULL_BUILD: true
matrix:
  fast_finish: true
platform:
  - x64
install:
  - cmd: |
      cd C:\Tools\vcpkg
      git log -1
      git fetch
      git checkout %VCPKG_HASH% -d
      git log -1
      copy /y "C:\projects\ffmpeg-msvc-build\vcpkg_acquire_msys.cmake" "C:\Tools\vcpkg\scripts\cmake\"
      .\bootstrap-vcpkg.bat -disableMetrics
      .\vcpkg.exe upgrade --no-dry-run
      .\vcpkg.exe integrate install
      .\vcpkg.exe install "ffmpeg[%FEATURES%]:%TRIPLET%" --recurse
      dir /s /b "installed\%TRIPLET%"
      cd C:\projects\ffmpeg-msvc-build\
  - ps: .\export.ps1 -triplet $env:TRIPLET -features $env:FEATURES -ErrorAction Stop
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmake -S test -B build -DCMAKE_BUILD_TYPE=RELEASE -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-md
  - cmake --build build
test: off
artifacts:
  - path: '*.7z'
deploy:
  description: 'Headers and libraries for FFmpeg.'
  provider: GitHub
  auth_token:
    secure: QSdxjkooPHApqh95gD9duaZBxmv/5zWzDcukjNQGmbedwEu0BvzgA6HUEXpvni25
  artifact: /ffmpeg.*\.7z/
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
    FULL_BUILD: true
cache:
  - c:\tools\vcpkg\installed\ -> appveyor.yml
