version: 1.0.{build}
image: Visual Studio 2019
environment:
  FEATURES: core,avcodec,avformat,avdevice,avfilter,swresample,swscale,bzip2,iconv,lzma,nvcodec,opus,snappy,soxr,vpx,wavpack,zlib
  VCPKG_HASH: 18ab4b72a26284f0df28295ce7bf9b21c96f20f4

  matrix:
    - TRIPLET: x64-windows-static-md
matrix:
  fast_finish: true
platform:
  - x64
build_script:
  - cmd: |
      pushd C:\Tools\vcpkg
      git log -1
      git fetch
      git checkout %VCPKG_HASH% -d
      git log -1
      git apply C:\projects\ffmpeg-msvc-build\9000-fix-cmake-platform-libs.patch
      .\bootstrap-vcpkg.bat -disableMetrics
      popd
  - ps: .\build.ps1 -triplet $env:TRIPLET -features $env:FEATURES -ErrorAction Stop
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - vcpkg integrate install
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-md ../test
  - ninja
  - cd ..
test: off
artifacts:
  - path: '*.7z'
deploy:
  description: 'Headers and libraries for FFmpeg.'
  provider: GitHub
  auth_token:
    secure: QSdxjkooPHApqh95gD9duaZBxmv/5zWzDcukjNQGmbedwEu0BvzgA6HUEXpvni25
  artifact: /ffmpeg.*\.7z/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
