version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
    - LINKAGE: shared
      LICENSE: GPL3
      RUNTIME_LIBRARY: MD
      TOOLSET: v141
    - LINKAGE: static
      LICENSE: GPL3
      RUNTIME_LIBRARY: MD
      TOOLSET: v141
    - LINKAGE: shared
      LICENSE: LGPL21
      RUNTIME_LIBRARY: MD
      TOOLSET: v141
    - LINKAGE: static
      LICENSE: LGPL21
      RUNTIME_LIBRARY: MD
      TOOLSET: v141
    - LINKAGE: shared
      LICENSE: GPL3
      RUNTIME_LIBRARY: MD
      TOOLSET: v140
    - LINKAGE: static
      LICENSE: GPL3
      RUNTIME_LIBRARY: MD
      TOOLSET: v140
    - LINKAGE: shared
      LICENSE: LGPL21
      RUNTIME_LIBRARY: MD
      TOOLSET: v140
    - LINKAGE: static
      LICENSE: LGPL21
      RUNTIME_LIBRARY: MD
      TOOLSET: v140
matrix:
  fast_finish: true
platform:
  - x86
  - x64
configuration: Release
install: install.bat
build_script: build.bat
test: off
artifacts:
  - path: '*.zip'
deploy:
  description: 'Headers, static/shared libraries, and executables for FFmpeg, built with msvc.'
  provider: GitHub
  auth_token:
    secure: QSdxjkooPHApqh95gD9duaZBxmv/5zWzDcukjNQGmbedwEu0BvzgA6HUEXpvni25
  artifact: /.*\.zip/
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true
