version: 1.0.{build}

image: Visual Studio 2015

environment:
  LINKAGE: Dynamic
  LICENSE: LGPL3
  RUNTIME_LIBRARY: MD

platform:
  - x64

configuration:
  - Release

install:
  - curl -o ffmpeg.tar.xz https://ffmpeg.zeranoe.com/builds/source/ffmpeg/ffmpeg-20170330-ad7aff0.tar.xz
  - 7z x ffmpeg.tar.xz
  - 7z x ffmpeg.tar
  - rename ffmpeg-20170330-ad7aff0 ffmpeg
  - mkdir c:\yasm
  - set PATH=c:\yasm;%PATH%
  - if "%PLATFORM%" == "x64" curl -o "c:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
  - if "%PLATFORM%" == "x86" curl -o "c:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win32.exe

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\build.bat'

test: off
