version: 1.0.{build}
image: Visual Studio 2015
environment:
  global:
    FFMPEG_VERSION: 20170330-ad7aff0
  matrix:
    - LINKAGE: shared
      LICENSE: GPL3
      RUNTIME_LIBRARY: MD
    - LINKAGE: static
      LICENSE: GPL3
      RUNTIME_LIBRARY: MD
    - LINKAGE: shared
      LICENSE: LGPL21
      RUNTIME_LIBRARY: MD
    - LINKAGE: static
      LICENSE: LGPL21
      RUNTIME_LIBRARY: MD
    - LINKAGE: shared
      LICENSE: GPL3
      RUNTIME_LIBRARY: MT
    - LINKAGE: static
      LICENSE: GPL3
      RUNTIME_LIBRARY: MT
    - LINKAGE: shared
      LICENSE: LGPL21
      RUNTIME_LIBRARY: MT
    - LINKAGE: static
      LICENSE: LGPL21
      RUNTIME_LIBRARY: MT
platform: x64
configuration: Release
install: install.bat
build_script: build.bat
test: off
artifacts:
  - path: '*.zip'
  - path: '*.nupkg'
