version: 1.0.{build}

image: Visual Studio 2015

environment:
  FFMPEG_VERSION: 20170330-ad7aff0
  LINKAGE: shared
  LICENSE: lgpl3
  RUNTIME_LIBRARY: md

platform: x64
configuration: Release
install: install.bat
build_script: build.bat
test: off
artifacts:
  - path: '*.zip'
