version: 1.0.{build}
image: Visual Studio 2015
environment:
  global:
    FFMPEG_VERSION: 20170330-ad7aff0
  matrix:
    - LINKAGE: shared
      LICENSE: LGPL21
      RUNTIME_LIBRARY: MD
platform: x64
configuration: Release
install: install.bat
build_script: build.bat
test: off
artifacts:
  - path: '*.zip'
  - path: '*.nupkg'
