version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
    - LINKAGE: shared
      RUNTIME_LIBRARY: MD
      TOOLSET: v141
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      LICENSE: LGPL21
    - LINKAGE: static
      RUNTIME_LIBRARY: MD
      TOOLSET: v141
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      LICENSE: LGPL21

    - LINKAGE: shared
      RUNTIME_LIBRARY: MD
      TOOLSET: v141
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      LICENSE: GPL3
    - LINKAGE: static
      RUNTIME_LIBRARY: MD
      TOOLSET: v141
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      LICENSE: GPL3

matrix:
  fast_finish: true
platform:
  - x86
  - x64
configuration: Release
install: install.bat
build_script: build.bat
test: off
artifacts:
  - path: '*.zip'
deploy:
  description: 'Headers, libraries, and executables for FFmpeg.'
  provider: GitHub
  auth_token:
    secure: QSdxjkooPHApqh95gD9duaZBxmv/5zWzDcukjNQGmbedwEu0BvzgA6HUEXpvni25
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
cache:
  - c:\nasm-2.14.02-win64.zip
