version: 1.0.{build}
image: Visual Studio 2019
environment:
  matrix:
    - LINKAGE: static
      RUNTIME_LIBRARY: MD
      TOOLSET: v142
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      FEATURES: core,vpx

matrix:
  fast_finish: true
platform:
  - x86
  - x64
build_script:
  # vcpkg in appveyor is broken, checkout latest working commit
  - pushd C:\Tools\vcpkg && git log -1 && popd
  - pushd C:\Tools\vcpkg && git checkout 077c0746be3773fdd443af52cbe5c3cc26379a15 && popd
  - pushd C:\Tools\vcpkg && git log -1 && popd
  - pushd C:\Tools\vcpkg && git apply "%APPVEYOR_BUILD_FOLDER%\ffmpeg-portfile-fix-debug-symbols.patch" && popd
  - ps: .\build.ps1 -platform $env:PLATFORM -runtime_library $env:RUNTIME_LIBRARY -linkage $env:LINKAGE -toolset $env:TOOLSET -features $env:FEATURES -ErrorAction Stop
test: off
artifacts:
  - path: '*.7z'
deploy:
  description: 'Headers and libraries for FFmpeg.'
  provider: GitHub
  auth_token:
    secure: QSdxjkooPHApqh95gD9duaZBxmv/5zWzDcukjNQGmbedwEu0BvzgA6HUEXpvni25
  artifact: /ffmpeg.*\.7z/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
