version: 1.0.{build}

image: Visual Studio 2015

environment:
  FFMPEG_VERSION: 20170330-ad7aff0
  LINKAGE: shared
  LICENSE: lgpl3
  RUNTIME_LIBRARY: md

platform:
  - x64

configuration:
  - Release

install:
  - curl -o source.tar.xz https://ffmpeg.zeranoe.com/builds/source/ffmpeg/ffmpeg-%FFMPEG_VERSION%.tar.xz
  - 7z x source.tar.xz
  - 7z x source.tar
  - mkdir c:\yasm
  - set PATH=c:\yasm;%PATH%
  - if "%PLATFORM%" == "x64" curl -o "c:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
  - if "%PLATFORM%" == "x86" curl -o "c:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win32.exe

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\build.bat'

test: off
