version: 1.0.{build}
image: Visual Studio 2015
environment:
  matrix:
    - LINKAGE: shared
      LICENSE: GPL3
      RUNTIME_LIBRARY: MD
    - LINKAGE: static
      LICENSE: GPL3
      RUNTIME_LIBRARY: MD
    - LINKAGE: shared
      LICENSE: LGPL21
      RUNTIME_LIBRARY: MD
    - LINKAGE: static
      LICENSE: LGPL21
      RUNTIME_LIBRARY: MD
platform: x64
configuration: Release
install: install.bat
build_script: build.bat
test: off
artifacts:
  - path: '*.zip'
deploy:
  description: 'Headers, static/shared libraries, and executables for FFmpeg, built with msvc.'
  provider: GitHub
  auth_token:
    secure: QSdxjkooPHApqh95gD9duaZBxmv/5zWzDcukjNQGmbedwEu0BvzgA6HUEXpvni25
  artifact: /.*\.zip/
  draft: true
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
